library(MASS)
Boston$chas <- as.factor(Boston$chas)
nrow(Boston)
ncol(Boston)
par(mfrow = c(2, 2))
plot(Boston$nox, Boston$crim)
plot(Boston$rm, Boston$crim)
plot(Boston$age, Boston$crim)
plot(Boston$dis, Boston$crim)
hist(Boston$crim, breaks = 50)
pairs(Boston[Boston$crim < 20, ])
hist(Boston$crim, breaks = 50)
nrow(Boston[Boston$crim > 20, ])
hist(Boston$tax, breaks = 50)
nrow(Boston[Boston$tax == 666, ])
hist(Boston$ptratio, breaks = 50)
nrow(Boston[Boston$ptratio > 20, ])
nrow(Boston[Boston$chas == 1, ])
median(Boston$ptratio)
row.names(Boston[min(Boston$medv), ])
range(Boston$tax)
Boston[min(Boston$medv), ]$tax
nrow(Boston[Boston$rm > 7, ])
nrow(Boston[Boston$rm > 8, ])
